// examples/with-mdx/src/entry-server.jsx
import { renderToStringAsync } from "solid-js/web";
import { StartServer, createHandler } from "solid-start/components";
import { inlineServerModules } from "solid-start/server";

function renderPage() {
  return async context => {
    let markup = await renderToStringAsync(() => <StartServer context={context} />);

    context.responseHeaders.set("Content-Type", "text/html");

    return new Response(markup, {
      status: 200,
      headers: context.responseHeaders
    });
  };
}

export default createHandler(inlineServerModules, renderPage);

// fixtures/bare/src/entry-server.tsx
import { StartServer, createHandler, renderAsync } from "solid-start/entry-server";
import { inlineServerModules } from "solid-start/server";
import { apiRoutes } from "solid-start/api";

export default createHandler(
  apiRoutes,
  inlineServerModules,
  renderAsync(context => <StartServer context={context} />)
);
